/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Michi' at '03.11.15 22:32' with Gradle 2.6
 *
 * @author Michi, @date 03.11.15 22:32
 */
public class Library {
    public boolean someLibraryMethods() {
        return true;
    }
}
